---
services:
  arm64_sysroot:
    container_name: py_arm_arm64_sysroot
    image: localhost:5000/runtime/py_arm/system:py_arm-ros2-humble-v1.0.0
    platform: linux/arm64
    volumes:
      - arm64_lib:/lib   # 直接挂载容器的/lib到卷
      - arm64_etc:/etc   # 直接挂载容器的/etc到卷
      - arm64_usr:/usr   # 直接挂载容器的/usr到卷
      - arm64_opt:/opt   # 直接挂载容器的/opt到卷

  amd64_crosscompile_arm64: 
    container_name: py_arm_amd64_crosscompile_arm64
    image: localhost:5000/${AMD64_CROSSCOMPILE_IMAGE:-amd64-crosscompile:v1.0.0}
    platform: linux/amd64
    network_mode: host # 配置网络模式为主机模式
    tty: true
    volumes:
      - arm64_lib:/sysroot/lib  # 卷映射到/sysroot/lib
      - arm64_etc:/sysroot/etc  # 卷映射到/sysroot/etc
      - arm64_usr:/sysroot/usr  # 卷映射到/sysroot/usr
      - arm64_opt:/sysroot/opt  # 卷映射到/sysroot/opt
      - /etc/timezone:/etc/timezone:rw
      - /etc/localtime:/etc/localtime:rw
      - ~/.ssh:/root/.ssh:rw
      - ./build.sh:/home/chunyu/build.sh:rw
      - ./toolchain.cmake:/home/chunyu/toolchain.cmake:r
      - ../../src:/home/chunyu/py_arm/src:rw
    depends_on:
      - arm64_sysroot
        
volumes:
  arm64_lib: {}
  arm64_etc: {}
  arm64_usr: {}
  arm64_opt: {}

