services:
  amd64_runtime:
    container_name: py_arm_amd64_runtime
    image: localhost:5000/runtime/py_arm/system:py_arm-ros2-humble-v1.0.0
    platform: linux/amd64
    tty: true
    privileged: true
    network_mode: host
    environment:
      DISPLAY: ${DISPLAY:-:1}
    volumes:
      - /etc/timezone:/etc/timezone:rw
      - /etc/localtime:/etc/localtime:rw
      - ~/.ssh:/root/.ssh:rw
      - ./build_x86.sh:/home/chunyu/build_x86.sh:rw
      - ../../src:/home/chunyu/py_arm:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
