services:
  py_arm_arm64_runtime : &default
    container_name: py_arm_arm64_runtime
    image: localhost:5000/runtime/py_arm/system:py_arm-ros2-humble-v1.0.0
    platform: linux/arm64
    network_mode: host
    tty: true
    restart: always
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /dev:/dev:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/dataset:/home/chunyu/dataset:rw
      - /tmp:/tmp:rw
      - /etc/asound.conf:/etc/asound.conf
      - /run/dbus:/run/dbus # for bluetooth
      - /var/run/dbus:/var/run/dbus:ro
      - /run/NetworkManager:/run/NetworkManager:ro
      - ~/.config/docker:/home/chunyu/version_info:rw
      - /usr/local/lib/camera-drv:/usr/local/lib/camera-drv:rw
    devices:
      - /dev/bus/usb
      - /dev/snd
    user: chunyu
